FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN go build -o api-core ./cmd/server/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/api-core .

EXPOSE 8080
CMD ["./api-core"]
